services:
  db:
      image: postgres:14.1-alpine
      container_name: postgres_db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      ports:
        - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/jedis
    ports:
      - "3000:3000"
    depends_on:
      - db
