default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres_db
  username: postgres
  password: password
  pool: 5


development:
  <<: *default
  database: jedis_development

test:
  <<: *default
  database: jedis_test

production:
  <<: *default
  database: jedis_production
  username: jedis
  password: <%= ENV['JEDIS_DATABASE_PASSWORD'] %>
